name: build-android
on:
  push:
    branches:
      - production
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - name: Confirm version
        run: echo $VERSION
      - uses: actions/checkout@v3
      - name: Import tool versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.0.1
        id: asdf
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.asdf.outputs.flutter }}
          channel: "stable"
          cache: true
      - name: Install packages
        run: flutter pub get
      - name: Build apk
        run: flutter build apk --build-name ${VERSION} --build-number ${{ github.run_number }}
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
