name: release-production
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create a new branch from tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          BRANCH_NAME=release/${TAG_NAME}
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME $TAG_NAME
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.branch_name }}
          title: "Release ${{ env.tag_name }}"
          body: |
            This pull request is automatically created for the release of tag ${{ env.tag_name }}.
          base: production
