name: release-production
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release to production
        run: |
          git checkout production
          git merge origin/main
          git push origin production
