name: release-production
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  merge-to-production:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions: write-all
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 全てのブランチを取得
      - name: Release to production
        run: |
          git checkout production
          git merge main
          git push origin production

  build:
    needs: merge-to-production
    uses: ./.github/workflows/build.yml
